stages:
  - apps
  - realms
  - clients

build-apps:
  stage: apps
  trigger:
    include: apps/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
      - apps/**/*

realms:
  stage: realms
  trigger:
    include: realms/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes: 
      - realms/**/*

clients:
  stage: clients
  trigger:
    include: clients/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes: 
      - clients/**/*
