stages:
- mirror
- scan
- mr
- dev
- preprod
- prod

include:
- project: 'core2471/ci-tools'
  file: 'mirror/mirror-repo.yml'
- project: 'core2471/ci-tools'
  file: 'scan/solar/solar-scan-code.yml'

check_apps:
  stage: mr
  trigger:
    include:
    - local: "apps/.gitlab-ci-mr.yml"
    strategy: depend
  except:
  - master
  - dev

build-apps:
  stage: dev
  trigger:
    include: apps/.gitlab-ci-dev.yml
    strategy: depend
  rules:
  - if: $CI_COMMIT_BRANCH == "dev"
    changes:
    - apps/**/*

realms:
  stage: dev
  trigger:
    include: realms/.gitlab-ci-dev.yml
    strategy: depend
  rules:
  - if: $CI_COMMIT_BRANCH == "dev"
    changes:
    - realms/**/*

clients:
  stage: dev
  trigger:
    include: clients/.gitlab-ci-dev.yml
    strategy: depend
  rules:
  - if: $CI_COMMIT_BRANCH == "dev"
    changes:
    - clients/**/*

# PREPROD deploy
build-apps-preprod:
  stage: preprod
  trigger:
    include: apps/.gitlab-ci-preprod.yml
    strategy: depend
  rules:
  - if: $PROD != "true" && $CI_COMMIT_BRANCH == "master"
    changes:
    - apps/**/*

realms-preprod:
  stage: preprod
  trigger:
    include: realms/.gitlab-ci-preprod.yml
    strategy: depend
  rules:
  - if: $PROD != "true" && $CI_COMMIT_BRANCH == "master"
    changes:
    - realms/**/*

clients-preprod:
  stage: preprod
  trigger:
    include: clients/.gitlab-ci-preprod.yml
    strategy: depend
  rules:
  - if: $PROD != "true" && $CI_COMMIT_BRANCH == "master"
    changes:
    - clients/**/*

### PROD deploy with Rules
build-apps-prod:
  stage: prod
  when: manual
  trigger:
    include: apps/.gitlab-ci-prod.yml
    strategy: depend
  rules:
  - if: $PROD == "true" && $CI_SERVER_URL == "https://gitlab.kacd.kz" && $CI_PIPELINE_SOURCE =~ "web|push" && $CI_COMMIT_BRANCH == "master"
    changes:
    - apps/**/*

realms-prod:
  stage: prod
  when: manual
  trigger:
    include: realms/.gitlab-ci-prod.yml
    strategy: depend
  rules:
  - if: $PROD == "true" && $CI_SERVER_URL == "https://gitlab.kacd.kz" && $CI_PIPELINE_SOURCE =~ "web|push" && $CI_COMMIT_BRANCH == "master"
    changes:
    - realms/**/*

clients-prod:
  stage: prod
  when: manual
  trigger:
    include: clients/.gitlab-ci-prod.yml
    strategy: depend
  rules:
  - if: $PROD == "true" && $CI_SERVER_URL == "https://gitlab.kacd.kz" && $CI_PIPELINE_SOURCE =~ "web|push" && $CI_COMMIT_BRANCH == "master"
    changes:
    - clients/**/*

### PROD-RC deploy

apps-prod-rc:
  stage: prod
  when: manual
  trigger:
    include: apps/.gitlab-ci-prod-rc.yml
    strategy: depend
  rules:
  - if: $PROD == "true" && $CI_SERVER_URL == "https://gitlab-rc.kacd.kz" && $CI_PIPELINE_SOURCE =~ "web|push" && $CI_COMMIT_BRANCH == "master"
  - when: never

realms-prod-rc:
  stage: prod
  when: manual
  trigger:
    include: realms/.gitlab-ci-prod-rc.yml
    strategy: depend
  rules:
  - if: $PROD == "true" && $CI_SERVER_URL == "https://gitlab-rc.kacd.kz" && $CI_PIPELINE_SOURCE =~ "web|push" && $CI_COMMIT_BRANCH == "master"
  - when: never

clients-prod-rc:
  stage: prod
  when: manual
  trigger:
    include: clients/.gitlab-ci-prod-rc.yml
    strategy: depend
  rules:
  - if: $PROD == "true" && $CI_SERVER_URL == "https://gitlab-rc.kacd.kz" && $CI_PIPELINE_SOURCE =~ "web|push" && $CI_COMMIT_BRANCH == "master"
  - when: never