version: '3'

services:

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    volumes:
      - ./themes:/opt/keycloak/themes
