apiVersion: sso.kacd.kz/v1
kind: Client
metadata:
  name: abs-plus
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: internal-realm
    kz-kacd-realm-name: internal
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  displayedName: ABS-PLUS
  displayedDescription: Клиент для присвоения ролей сотрудникам бэкофис 
  access:
    validRedirectUris:
    - http://localhost
    webOrigins:
    - "+"
  capability:
    type: PUBLIC
  roles:
  - name: backoffice-bsdh-admin-panel-read
    roleDescription: Просмотр информации о состояниях обработчиков
  - name: backoffice-bsdh-admin-panel-create
    roleDescription: Создание процессов и данных в справочниках
  - name: backoffice-bsdh-admin-panel-update
    roleDescription: Изменение состояний процессов и данных в обработчиках
