apiVersion: sso.kacd.kz/v1
kind: Client
metadata:
  name: camunda-operate
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    kz-kacd-realm-name: internal
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  displayedName: Client for camunda operate
  displayedDescription: Client for camunda operate
  access:
    validRedirectUris:
    {{- include "common.tplvalues.render" ( dict "value" .Values.clients.camundaOperate.redirectUris "context" $ ) | nindent 4 }}
    webOrigins:
    {{- include "common.tplvalues.render" ( dict "value" .Values.clients.camundaOperate.webOrigins "context" $ ) | nindent 4 }}
  capability:
    type: PUBLIC
  attributes: []
  roles: []
