apiVersion: sso.kacd.kz/v1
kind: Client
metadata:
  name: currencyratekuber
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: intenral-realm
    kz-kacd-realm-name: internal
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  displayedName: currencyratekuber
  displayedDescription: currencyratekuber
  access:
    validRedirectUris:
    {{- include "common.tplvalues.render" ( dict "value" .Values.clients.currencyRateKuber.redirectUris "context" $ ) | nindent 4 }}
    webOrigins:
    {{- include "common.tplvalues.render" ( dict "value" .Values.clients.currencyRateKuber.webOrigins "context" $ ) | nindent 4 }}
  capability:
    type: PUBLIC
  attributes:
  - DIVISION
  roles: []

