apiVersion: sso.kacd.kz/v1
kind: Client
metadata:
  name: deponent-report
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: internal-realm
    kz-kacd-realm-name: internal
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  displayedName: Deponent accounts report service
  displayedDescription: Формирование выписки для депонентов  по лицевому счету
  access:
    validRedirectUris:
    {{- include "common.tplvalues.render" ( dict "value" .Values.clients.deponentReport.redirectUris "context" $ ) | nindent 4 }}
    webOrigins:
    {{- include "common.tplvalues.render" ( dict "value" .Values.clients.deponentReport.webOrigins "context" $ ) | nindent 4 }}
  capability:
    type: CONFIDENTIAL
    clientExistingSecret: deponent-report-secret
    clientSecretKey: client_secret
  scope:
    name: deponent_report
    scopeDescription: Получить доступ к API формировании выписки для депонентов по лицевому счету
  roles: []
