apiVersion: sso.kacd.kz/v1
kind: Client
metadata:
  name: management-company-front
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: external-realm
    kz-kacd-realm-name: external
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  displayedName: Front-End for Management Company
  displayedDescription: Фронт для раздела ЛК Эмитент Управляющая компания (ПИФ)
  access:
    validRedirectUris:
    - http://localhsot:4200
    webOrigins:
    - "+"
  capability:
    type: PUBLIC
  attributes:
  - POSITION
  - FIRST_NAME
  - LAST_NAME
  - MIDDLE_NAME
  - GROUPS
  - LOCALE
  - IIN
  - PHONE_NUMBER
  roles: 
  - name: editor
    roleDescription: Доступ на чтение и редактирование
  - name: reader
    roleDescription: Доступ только на чтение
