apiVersion: sso.kacd.kz/v1
kind: Client
metadata:
  name: matrix
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: external-realm
    kz-kacd-realm-name: external
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  displayedName: matrix synapse 
  displayedDescription: Matrix чат 
  access:
    validRedirectUris:
    {{- include "common.tplvalues.render" ( dict "value" .Values.clients.matrix.redirectUris "context" $ ) | nindent 4 }}
    webOrigins:
    {{- include "common.tplvalues.render" ( dict "value" .Values.clients.matrix.webOrigins "context" $ ) | nindent 4 }}
  capability:
    type: CONFIDENTIAL
    clientExistingSecret: matrix-secret
    clientSecretKey: client_secret
  roles: []
