apiVersion: sso.kacd.kz
kind: Client
metadata:
  name: mt535
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: intenral-realm
    kz-kacd-realm-name: internal
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  displayedName: MT 535
  displayedDescription: Автоматизация процесса сверки по выпискам c YO (MT535)
  access:
    validRedirectUris:
    - http://localhost:8082/*
    - http://10.10.125.4:8085/*
    webOrigins:
    - "+"
  capability:
    type: PUBLIC
