apiVersion: sso.kacd.kz/v1
kind: Client
metadata:
  name: odd
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: internal-realm
    kz-kacd-realm-name: internal
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  displayedName: ODD
  displayedDescription: ODD client
  access:
    validRedirectUris:
    - http://localhost
    webOrigins:
    - "+"
  capability:
    type: PUBLIC
  roles:
  - name: odd_manager
    roleDescription: ODD MANAGER
