apiVersion: sso.kacd.kz/v1
kind: Client
metadata:
  name: pay-agent
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: internal-realm
    kz-kacd-realm-name: internal
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  displayedName: pay-agent
  displayedDescription: Сервис pay-agent предназначен для автоматизации процесса выплаты дохода в рамках оказания услуг платежного агента для команды ЛКД
  access:
    validRedirectUris:
    - http://localhsot:4200
    webOrigins:
    - "+"
  capability:
    type: CONFIDENTIAL
    clientExistingSecret: payagnt-secret
    clientSecretKey: client_secret
  attributes:
  - FIRST_NAME
  - LAST_NAME
  - MIDDLE_NAME
  - GROUPS
  - LOCALE
  roles: [{
    name: backoffice-payagnt-reader,
    roleDescription: 'Просмотр журнала возвратов'
  }, {
    name: backoffice-payagnt-signer,
    roleDescription: 'Полный доступ к разделу Платежный агент просмотр/подтверждение/отклонение'
  }]