apiVersion: sso.kacd.kz/v1
kind: Client
metadata:
  name: tax-qi-service
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: external-realm
    kz-kacd-realm-name: external
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  displayedName: TAX-QI-SERVICE
  displayedDescription: Клиент для присвоения ролей депонентам
  access:
    validRedirectUris:
    - http://localhost
    webOrigins:
    - "+"
  capability:
    type: CONFIDENTIAL
    clientExistingSecret: tax-qi-service-secret
    clientSecretKey: client_secret
  attributes:
  - FIRST_NAME
  - LAST_NAME
  - MIDDLE_NAME
  - GROUPS
  - LOCALE
  roles: [{
    name: reader,
    roleDescription: 'Просмотр сведений раздела Налоги сотрудником депонента'
  }, {
    name: sender,
    roleDescription: 'Управление (изменение, удаление) налоговых форм сотрудником депонента'
  }, {
    name: signer,
    roleDescription: 'Подписание анкеты сотрудником депонента'
  }]
