apiVersion: sso.kacd.kz/v1beta1
kind: Client
metadata:
  name: test-client
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: intenral-realm
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  displayedName: "My Test Client"
  description: For test purposes only!
  realm: internal
  access:
    rootUrl: http://example.com
    homeUrl: /account
    validRedirectUris:
      - "/account/*"
    webOrigins:
      - "+"
  ldap:
    dn: OU=test-client,OU=OU_Roles,DC=tstcsdepo,DC=net
  attributes: ["MIDDLE_NAME", "LOCALE", "GROUPS"]
  roles:
    - name: ultra-user
      description: This is ultra ultra user
    - name: simple-user
      description: This is simple simple user
  allowedGroup: admin