apiVersion: sso.kacd.kz/v1
kind: Client
metadata:
  name: uncalimed-money
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: internal-realm
    kz-kacd-realm-name: internal
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  displayedName: uncalimed-money
  displayedDescription: модуль Выплаты ИД и налоги
  access:
    validRedirectUris:
    - http://localhsot:4200
    webOrigins:
    - "+"
  capability:
    type: PUBLIC
  attributes:
  - FIRST_NAME
  - LAST_NAME
  - MIDDLE_NAME
  - GROUPS
  - LOCALE
  roles:
  - name: read_only
    roleDescription: Только чтение
  - name: fo_signer
    roleDescription: ФО - фронт офис - подписывающий
  - name: obu_signer
    roleDescription: ОБУ - бухгалтерия - подписывающий
