apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clients.sso.kacd.kz
spec:
  group: sso.kacd.kz
  names:
    kind: Client
    plural: clients
    shortNames:
    - clt
    singular: client
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              realm:
                description: Name of the realm
                type: string
              displayedName:
                description: Name to be displayed in admin console
                type: string
              description:
                description: Full specified description of the client. Can be multiline
                  string
                type: string
              access:
                description: Settings of the access of client
                properties:
                  rootUrl:
                    description: Root url of the client
                    type: string
                  homeUrl:
                    description: "Home path of the client (this link will be used\
                      \ when keycloak needs to link client home page). If you already\
                      \ have specified rootUrl, you need just specify path after rootUrl\
                      \ to visit home page."
                    type: string
                  validRedirectUris:
                    description: "List of valid redirect uris. Redirect URI-s are\
                      \ URI-s which can be used by client to log in user. If you use\
                      \ rootUrl, you can just specify path after rootUrl. You can\
                      \ use wildcard patterns. E.g. https://myapp/app1/*"
                    items:
                      type: string
                    type: array
                  webOrigins:
                    description: List of web origins which will be permitted to access
                      keycloak. It specifies CORS policies. You can just include single
                      element '+' to include in this list all origins from validRedirectUris.
                    items:
                      type: string
                    type: array
                type: object
              capability:
                description: Setting of client capabilities
                properties:
                  type:
                    description: "Type of the client. By default it is PUBLIC. PUBLIC\
                      \ means that client has no client secret and can authenticate\
                      \ users only using standard OAuth2.0 flow. CONFIDENTIAL means\
                      \ that the client has ability to protect it's secret data, so\
                      \ it can authenticate users using password access grand and\
                      \ can issue access token using it's own credentials. BEARER_ONLY\
                      \ means that this is resource server which can't authenticate\
                      \ users at all, so, it only can receive bearer tokens."
                    enum:
                    - PUBLIC
                    - CONFIDENTIAL
                    - BEARER_ONLY
                    type: string
                  clientExistingSecret:
                    description: "If type of the client is confidential, it requires\
                      \ client_secret to log in. clientExistingSecret is name of secret\
                      \ wich contains this secret value. If no one has specified,\
                      \ client_secret will be generated randomly."
                    type: string
                  clientSecretKey:
                    description: "If type of the client is confidential, it requires\
                      \ client_secret to log in. clientSecretKey specifies key of\
                      \ the clientExistingSecret data wich contains secret value."
                    type: string
                type: object
              ldap:
                description: Settings of the ldap roles mappings if ldap is configured
                  on this realm
                properties:
                  dn:
                    description: Full specified DN name of the roles specific for
                      this client
                    type: string
                type: object
              attributes:
                description: List of the attributes which will be additional mapped
                  to id token and userinfo.
                items:
                  enum:
                  - FIRST_NAME
                  - LAST_NAME
                  - MIDDLE_NAME
                  - GROUPS
                  - LOCALE
                  - DIVISION
                  type: string
                type: array
              roles:
                description: List of the roles which defined inside client.
                items:
                  properties:
                    name:
                      description: Name of the role. This name will be propagated
                        into tokens.
                      type: string
                    description:
                      description: Description of the role. It can be multiline string.
                      type: string
                  type: object
                type: array
              allowedGroup:
                description: Strict authentication only for users in group
                type: string
            type: object
          status:
            properties:
              state:
                description: State of the client
                enum:
                - APPLYING
                - APPLIED
                - FAILED
                - BACKOFF
                - WAITING_FOR_REALM
                type: string
              message:
                description: Description of the state
                type: string
              generation:
                description: Last applied generation
                type: integer
              lastApplication:
                description: Time of the last try to apply client
                type: string
              backoffSeconds:
                description: Time to backoff in seconds
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
