apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-env-vars" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  KEYCLOAK_ADMIN: {{ .Values.auth.adminUser | quote }}
  KC_HOSTNAME: {{ .Values.hostname | quote }}
  KC_HOSTNAME_ADMIN: {{ .Values.hostname | quote }}
  KC_HTTP_PORT: {{ .Values.containerPorts.http | quote }}
  KC_PROXY: {{ .Values.proxy | quote }}
  KC_METRICS_ENABLED: {{ ternary "true" "false" .Values.metrics.enabled | quote }}
  KC_DB_URL_HOST: {{ .Values.database.host | quote }}
  KC_DB_URL_PORT: {{ .Values.database.port | quote }}
  KC_DB_URL_DATABASE: {{ .Values.database.name | quote }}
  KC_DB_USERNAME: {{ .Values.database.username | quote }}
  KC_DB_SCHEMA: {{ .Values.database.schema | quote }}
  KC_HTTP_RELATIVE_PATH: {{ .Values.httpRelativePath | quote }}
  KC_HTTPS_CERTIFICATE_FILE: {{ printf "/opt/kacd/keycloak/certs/%s" .Values.tls.certificateFileKey }}
  KC_HTTPS_CERTIFICATE_KEY_FILE: {{ printf "/opt/kacd/keycloak/certs/%s" .Values.tls.keyFileKey }}
  KC_HTTPS_PORT: {{ .Values.containerPorts.https | quote }}
  MASTER_REALM_ENABLED: {{ .Values.enabledMasterRealm | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  KC_SIGN_NCA_URL: {{ .Values.ncaUrl | quote }}
  MKB_URL: {{ .Values.mkbUrl | quote }}
  AUTH_DEBUG_MODE: {{ .Values.debugAuth | quote }}
{{- if (include "keycloak.createConfigmap" .) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configuration" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  keycloak.conf: |-
    {{- .Values.configuration | nindent 4 }}
{{- end }}
{{- if .Values.initialSetup }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-realms" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  internal.yaml: |-
    apiVersion: sso.kacd.kz/v1
    kind: Realm
    metadata:
      name: internal
    spec:
      displayedName: KCSD
  external.yaml: |-
    apiVersion: sso.kacd.kz/v1
    kind: Realm
    metadata:
      name: external
    spec:
      displayedName: KCSD
  afr.yaml: |-
    apiVersion: sso.kacd.kz/v1
    kind: Realm
    metadata:
      name: afr
    spec:
      displayedName: AFR
{{- end }}