realm:
  # Default namespace where controller should watch changes
  namespace: sso
  # URL to keycloak
  keycloak: http://localhost
  # Admin user of keycloak
  user: admin
  # Password of admin user of keycloak
  password: test

