global:
  imageRegistry: nexus.kacd.kz:5000
  imagePullSecrets:
  - kacd-docker-creds

image: nexus.kacd.kz:5000/valyayev/test/keycloak:0.3

replicaCount: 1

hostname: sso-dev.k8s-dev.kacd.kz

enabledMasterRealm: "true"

resources:
  limits:
    memory: "4Gi"
    cpu: "4"
  requests:
    memory: "1Gi"
    cpu: "1"

ncaUrl: https://kcsd-secure-nca.k8s-dev.kacd.kz/platform/services/secure/nca/auth/v1/authenticate

tls:
  enabled: true
  existingSecret: kacd-tls
  certificateFileKey: tls.crt
  keyFileKey: tls.key

auth:
  adminUser: admin
  existingSecret: "sso-keycloak-admin-password"
  existingSecretPasswordKey: password

database:
  host: psql-dev.kacd.kz
  name: keycloak
  schema: auth
  username: keycloak
  existingSecret: sso-keycloak-database-password
  existingSecretPasswordKey: password

redis:
  host: keycloak-redis.sso.svc.cluster.local
  port: 6379

kafka:
  enabled: true
  bootstrapServers: "kafka-dev.kacd.kz:9092"
  groupId: keycloak-dev

service:
  type: ClusterIP
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"

ingress:
  enabled: true
  hostname: sso-dev.k8s-dev.kacd.kz
  tls: true
  secretName: kacd-tls

realmController:
  enabled: true
  image: nexus.kacd.kz:5000/platform/sso/realm-controller:dev-1377
