
## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - name: myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""

# Image of the keycloak
image: nexus.kacd.kz:5000/platform/sso/keycloak:0.3

initialSetup: false

#
# Service account settings
#
serviceAccount:
  #
  # Name of existing service account
  #
  name: default

#
# Overriding keycloak container command if needed
# E.g. ["/opt/keycloak/bin/kc.sh", "start-dev"]
#
command: []

#
# Overriding default container args
#
args: []

#
# Keycloak resource requests and limits
# ref: https://kubernetes.io/docs/user-guide/compute-resources/
#
resources:
  limits: {}
  requests: {}

hostname: localhost

#
# Value of configuration
# It will create new ConfigMap with this data
#
configuration: ""

#
# Name of the existing configmap with keycloak.conf inside
# This value overrides configuration parameter
#
existingConfigmap: ""

#
# base path of keycloak
#
httpRelativePath: "/"

#
# Is master realm enabled
#
enabledMasterRealm: "false"

# 
# Posrts of keycloak inside container
#
# http - port of HTTP (plain text) endpoint (using only in development mode)
# https - port of HTTP with TLS endpoint (using in production)
#
containerPorts:
  http: 8080
  https: 8443

#
# reverse Proxy mode edge, reencrypt, passthrough or none
# ref: https://www.keycloak.org/server/reverseproxy
#
proxy: passthrough

#
# Settings of keycloak metrics
#
metrics:
  #
  # If true keycloak will collect it's metrics.
  #
  enabled: true

#
# TLS config. It's required to run keycloak in production mode.
#
tls:
  #
  # If enabled true tls certificates will be mount inside keycloak container
  #
  enabled: true
  #
  # Name of the secret with tls data.
  #
  existingSecret: ""
  #
  # Name of the certificate file inside existing secret
  #
  certificateFileKey: server.crt
  #
  # Name of the key file inside existing secret
  #
  keyFileKey: server.key

#
# Admin authorization config
#
auth:
  #
  # Name of the admin user
  #
  adminUser: admin
  #
  # Password of the admin user
  #
  adminPassword: ""
  #
  # Or existing secret which contains admin password
  #
  existingSecret: ""
  #
  # Key of the value of admin password secret
  #
  existingSecretPasswordKey: "password"

#
# Configuration of database connection
#
database:
  #
  # Host of the database
  #
  host: ""
  #
  # Port of the database
  #
  port: 5432
  #
  # Name of the database
  #
  name: postgres
  #
  # Name of database schema
  #
  schema: public
  #
  # Name of the database user
  #
  username: postgres
  #
  # Password of the database
  #
  password: ""
  #
  # Existing secret which contains database connectivity password
  #
  existingSecret: ""
  #
  # Key in the secret which contains password
  #
  existingSecretPasswordKey: ""

#
# Configuration to access redis
#
redis:
  host: localhost
  port: '6379'

#
# Realm controller config
#
realmController:
  enabled: false
  #
  # Image of the controller
  #
  image: nexus.kacd.kz:5000/platform/sso/realm-controller:0.1
  #
  # Annotations on pod
  #
  podAnnotations: []
  #
  # Labels on pod
  #
  podLabels: []

#
# Value to override default full qualified name of the recources
#
fullnameOverride: ""

#
# Value to override partial name of the recources
#
nameOverride: ""

#
# Value to override standard namespace
#
namespaceOverride: ""

#
# Common labels to add to all created objects
# E.g.
#    commonLabels:
#      prometheus.io/scrape: true
#
commonLabels: {}

#
# Common annotations to add to stateful sets
#
commonAnnotations: {}

#
# Count of replicas of keycloak
#
replicaCount: 1

#
# Update strategy for rolling update.
# Define here whole object of kubernetes's update strategy.
# ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies
#
updateStrategy:
  type: RollingUpdate
  rollingUpdate: {}

#
# List of labels which will be added only on pod
#
podLabels: {}
#
# List of labels which will be added only on pod
#
podAnnotations: {}

## @param nodeSelector Node labels for pod assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}
## @param tolerations Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []
## @param topologySpreadConstraints Topology Spread Constraints for pod assignment spread across your cluster among failure-domains. Evaluated as a template
## Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#spread-constraints-for-pods
##
topologySpreadConstraints: []
## @param priorityClassName Keycloak pods' Priority Class Name
## ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
##
priorityClassName: ""
## @param schedulerName Use an alternate scheduler, e.g. "stork".
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
schedulerName: ""
## @param terminationGracePeriodSeconds Seconds Keycloak pod needs to terminate gracefully
## ref: https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods
##
terminationGracePeriodSeconds: ""
## @param lifecycleHooks LifecycleHooks to set additional configuration at startup
##
lifecycleHooks: {}
## Keycloak containers' Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
## @param containerSecurityContext.enabled Enabled Keycloak containers' Security Context
## @param containerSecurityContext.runAsUser Set Keycloak container's Security Context runAsUser
## @param containerSecurityContext.runAsNonRoot Set Keycloak container's Security Context runAsNonRoot
##
containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true
## @param extraEnvVars Extra environment variables to be set on Keycloak container
## Example:
## extraEnvVars:
##   - name: FOO
##     value: "bar"
##
extraEnvVars: []
## Keycloak logging configuration
## ref: https://www.keycloak.org/server/logging
## @param logging.output Alternates between the default log output format or json format
##
logging:
  output: default
## Keycloak pods' SecurityContext
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
## @param podSecurityContext.enabled Enabled Keycloak pods' Security Context
## @param podSecurityContext.fsGroup Set Keycloak pod's Security Context fsGroup
##
podSecurityContext:
  enabled: true
  fsGroup: 1001
## @param clusterDomain Default Kubernetes cluster domain
##
clusterDomain: cluster.local
## @param podManagementPolicy Pod management policy for the Keycloak statefulset
##
podManagementPolicy: Parallel
## Service configuration
##
service:
  ## @param service.type Kubernetes service type
  ##
  type: LoadBalancer
  ## @param service.http.enabled Enable http port on service
  ##
  http:
    enabled: true
  ## @param service.ports.http Keycloak service HTTP port
  ## @param service.ports.https Keycloak service HTTPS port
  ##
  ports:
    http: 80
    https: 443
  ## @param service.nodePorts [object] Specify the nodePort values for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  nodePorts:
    http: ""
    https: ""
  ## @param service.sessionAffinity Control where client requests go, to the same pod or round-robin
  ## Values: ClientIP or None
  ## ref: https://kubernetes.io/docs/user-guide/services/
  ##
  sessionAffinity: None
  ## @param service.sessionAffinityConfig Additional settings for the sessionAffinity
  ## sessionAffinityConfig:
  ##   clientIP:
  ##     timeoutSeconds: 300
  ##
  sessionAffinityConfig: {}
  ## @param service.clusterIP Keycloak service clusterIP IP
  ## e.g:
  ## clusterIP: None
  ##
  clusterIP: ""
  ## @param service.loadBalancerIP loadBalancerIP for the SuiteCRM Service (optional, cloud specific)
  ## ref: https://kubernetes.io/docs/user-guide/services/#type-loadbalancer
  ##
  loadBalancerIP: ""
  ## @param service.loadBalancerSourceRanges Address that are allowed when service is LoadBalancer
  ## https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
  ## Example:
  ## loadBalancerSourceRanges:
  ##   - 10.10.10.0/24
  ##
  loadBalancerSourceRanges: []
  ## @param service.externalTrafficPolicy Enable client source IP preservation
  ## ref https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  ##
  externalTrafficPolicy: Cluster
  ## @param service.annotations Additional custom annotations for Keycloak service
  ##
  annotations: {}
  ## @param service.extraPorts Extra port to expose on Keycloak service
  ##
  extraPorts: []
## Keycloak ingress parameters
## ref: https://kubernetes.io/docs/user-guide/ingress/
##
ingress:
  ## @param ingress.enabled Enable ingress record generation for Keycloak
  ##
  enabled: false
  ## @param ingress.ingressClassName IngressClass that will be be used to implement the Ingress (Kubernetes 1.18+)
  ## This is supported in Kubernetes 1.18+ and required if you have more than one IngressClass marked as the default for your cluster .
  ## ref: https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/
  ##
  ingressClassName: ""
  ## @param ingress.pathType Ingress path type
  ##
  pathType: Prefix
  ## @param ingress.hostname Default host for the ingress record (evaluated as template)
  ##
  hostname: keycloak.local
  ## @param ingress.path Default path for the ingress record
  ##
  path: /
  ## @param ingress.servicePort Backend service port to use
  ## Default is http. Alternative is https.
  ##
  servicePort: http
  ## @param ingress.annotations [object] Additional annotations for the Ingress resource. To enable certificate autogeneration, place here your cert-manager annotations.
  ## Use this parameter to set the required annotations for cert-manager, see
  ## ref: https://cert-manager.io/docs/usage/ingress/#supported-annotations
  ## e.g:
  ## annotations:
  ##   kubernetes.io/ingress.class: nginx
  ##   cert-manager.io/cluster-issuer: cluster-issuer-name
  ##
  annotations: {}
  ## @param ingress.tls Enable TLS configuration for the host defined at `ingress.hostname` parameter
  ## TLS certificates will be retrieved from a TLS secret with name: `{{- printf "%s-tls" (tpl .Values.ingress.hostname .) }}`
  ## You can:
  ##   - Use the `ingress.secrets` parameter to create this TLS secret
  ##   - Rely on cert-manager to create it by setting the corresponding annotations
  ##   - Rely on Helm to create self-signed certificates by setting `ingress.selfSigned=true`
  ##
  tls: false
  ## @param ingress.selfSigned Create a TLS secret for this ingress record using self-signed certificates generated by Helm
  ##
  selfSigned: false
  ## @param ingress.extraHosts An array with additional hostname(s) to be covered with the ingress record
  ## e.g:
  ## extraHosts:
  ##   - name: keycloak.local
  ##     path: /
  ##
  extraHosts: []
  ## @param ingress.extraPaths Any additional arbitrary paths that may need to be added to the ingress under the main host.
  ## For example: The ALB ingress controller requires a special rule for handling SSL redirection.
  ## extraPaths:
  ## - path: /*
  ##   backend:
  ##     serviceName: ssl-redirect
  ##     servicePort: use-annotation
  ##
  extraPaths: []
  ## @param ingress.extraTls The tls configuration for additional hostnames to be covered with this ingress record.
  ## see: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
  ## extraTls:
  ## - hosts:
  ##     - keycloak.local
  ##   secretName: keycloak.local-tls
  ##
  extraTls: []
  ## @param ingress.secrets If you're providing your own certificates, please use this to add the certificates as secrets
  ## key and certificate should start with -----BEGIN CERTIFICATE----- or
  ## -----BEGIN RSA PRIVATE KEY-----
  ##
  ## name should line up with a tlsSecret set further up
  ## If you're using cert-manager, this is unneeded, as it will create the secret for you if it is not set
  ##
  ## It is also possible to create and manage the certificates outside of this helm chart
  ## Please see README.md for more information
  ## e.g:
  ## - name: keycloak.local-tls
  ##   key:
  ##   certificate:
  ##
  secrets: []
  ## @param ingress.extraRules Additional rules to be covered with this ingress record
  ## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-rules
  ## e.g:
  ## extraRules:
  ## - host: airflow.local
  ##     http:
  ##       path: /
  ##       backend:
  ##         service:
  ##           name: airflow-svc
  ##           port:
  ##             name: http
  ##
  extraRules: []
