clients:
  afrAuthorityServicesFront:
    redirectUris:
    - http://localhost:4200/*
    - https://ardfm.k8s-dev.kacd.kz/*
    webOrigins:
    - http://localhost:4200
    - https://ardfm.k8s-dev.kacd.kz
  deponentReport:
    redirectUris:
    - http://localhost:8080/*
    webOrigins:
    - "+"
  lkShellBack:
    redirectUris:
    - http://localhost:8080/*
    webOrigins:
    - "+"
  lkShellFront:
    redirectUris:
    - https://kacd-lk-shell.k8s-dev.kacd.kz/*
    - http://localhost:4200/*
    - http://kacd-lk-shell.k8s-dev.kacd.kz/*
    webOrigins:
    - https://kacd-lk-shell.k8s-dev.kacd.kz
    - http://localhost:4200
    - http://kacd-lk-shell.k8s-dev.kacd.kz
  lkShellFrontInternal:
    redirectUris:
    - https://kacd-lk-shell.k8s-dev.kacd.kz/admin/*
    - http://localhost:4200/admin/*
    - http://kacd-lk-shell.k8s-dev.kacd.kz/admin/*
    webOrigins:
    - https://kacd-lk-shell.k8s-dev.kacd.kz
    - http://localhost:4200
    - http://kacd-lk-shell.k8s-dev.kacd.kz
  mt535:
    redirectUris:
    - http://localhost:8184/*
    - http://10.10.125.4:8085/*
    webOrigins:
    - "+"
  armFrontOffice:
    redirectUris:
    - http://localhost:8080/*
    - https://arm-front.k8s-dev.kacd.kz/*
    webOrigins:
    - http://localhost:8080
    - https://arm-front.k8s-dev.kacd.kz
  billing:
    redirectUris:
    - http://localhost:4200/*
    - https://billing-dev.k8s-dev.kacd.kz/*
    - https://billing-preprod.k8s-preprod.kacd.kz/*
    webOrigins:
    - http://localhost:4200
    - https://billing-dev.k8s-dev.kacd.kz
    - https://billing-preprod.k8s-preprod.kacd.kz
  tophrInternal:
    redirectUris:
    - https://tophr-preprod.kcsd.kz/*
    webOrigins:
    - https://tophr-preprod.kcsd.kz