clients:
  afrAuthorityServicesFront:
    redirectUris:
    - https://ardfm.kacd.kz/*
    webOrigins:
    - https://ardfm.kacd.kz
  deponentReport:
    redirectUris:
    - http://localhost:8080/*
    webOrigins:
    - "+"
  lkShellBack:
    redirectUris:
    - http://localhost:8080/*
    webOrigins:
    - "+"
  lkShellFront:
    redirectUris:
    - https://cabinet.kacd.kz/*
    webOrigins:
    - https://cabinet.kacd.kz
  lkShellFrontInternal:
    redirectUris:
    - https://backoffice.kacd.kz/*
    webOrigins:
    - https://backoffice.kacd.kz
  mt535:
    redirectUris:
    - http://10.10.125.4:8085/*
    webOrigins:
    - "+"
  armFrontOffice:
    redirectUris:
    - https://fo.kacd.kz/*
    webOrigins:
    - https://fo.kacd.kz
  billing:
    redirectUris:
    - https://billing.kacd.kz/*
    webOrigins:
    - https://billing.kacd.kz
  tophrInternal:
    redirectUris:
    - https://tophr.kcsd.kz/*
    webOrigins:
    - https://tophr.kcsd.kz
