#
# Override namespace of the release
#
namespaceOverride: ""

#
# Sets common labels on all objects created
#
commonLabels: {}

#
# Sets common annotations on all objects created
#
commonAnnotations: {}

#
# Settings for test client
#
testClient:
  #
  # Distinguished name to search roles
  #
  rolesDn: ""
