annotations:
  category: DeveloperTools
apiVersion: v2
appVersion: 19.0.3
description: Chart to deploy redis for keycloak.
home: https://www.keycloak.org
name: redis
sources:
- https://github.com/keycloak/keycloak
version: 0.0.1
