#
# Override namespace of the release
#
namespaceOverride: ""

#
# Sets common labels on all objects created
#
commonLabels: {}

#
# Sets common annotations on all objects created
#
commonAnnotations: {}

imagePullSecrets: []

image: nexus.kacd.kz:5000/platform/sso/redis:7.0.9-alpine
