version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    command: ["start-dev"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_PASSWORD=keycloak
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak?user=postgres
      - KC_LOG_LEVEL=info
      - YAML_MODE=true
      - YAML_CLIENTS_DIRECTORY=/opt/keycloak/clients
    volumes:
      - /Users/almatsagandykov/IdeaProjects/sso7/apps/extensions/common-extensions/target/common-extensions-23.0.0-jar-with-dependencies.jar:/opt/keycloak/providers/common-extensions.jar:rw
      - /Users/almatsagandykov/IdeaProjects/sso7/apps/extensions/common-extensions/test-realm.yaml:/opt/keycloak/.kacd/import/test-realm.yaml
      - /Users/almatsagandykov/IdeaProjects/sso7/apps/extensions/common-extensions/cache-ispn.xml:/opt/keycloak/config/cache-ispn.xml
      - /Users/almatsagandykov/IdeaProjects/sso7/test-clients:/opt/keycloak/clients
    ports:
      - "8085:8080"
  postgres:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=keycloak
    - POSTGRES_DB=keycloak
    ports:
    - "5439:5432"
  redis:
    image: redis:7.0.9-alpine
    ports:
    - "6379:6379"
  redisinsight:
    image: redislabs/redisinsight:1.13.1
    ports:
    - "8001:8001"
