stages:
  - prebuild
  - cache
  - build-docker
  - dev-deploy

build-ldap-extension:
  stage: prebuild
  image: maven:3-eclipse-temurin-17-alpine
  before_script:
    - apk add curl
    - export PROJECT_DIR="apps/extensions/ldap-mappers"
    - cd ${PROJECT_DIR}
    - export NEXUS_REPO="https://kacd.nexus.kz/repository/kacd-raw-hosted/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_COMMIT_REF_SLUG}/${CI_PIPELINE_ID}/ldap-mappers.jar"
    - export MAVEN_OPTS="-Dmaven.repo.local=${CI_PROJECT_DIR}/${PROJECT_DIR}/.m2"
  script:
    - mvn clean package
    - curl -v --user '${NEXUS_RAW_REPO}' --upload-file ./target/ldap-mappers.jar ${NEXUS_REPO}
  cache:
    - key: m2
      paths:
        - apps/extensions/ldap-mappers/.m2
  tags:
    - global_runner_2

cache-artifacts:
  stage: cache
  image: alpine:latest
  before_script:
    - apk add curl
    - export NEXUS_REPO="https://kacd.nexus.kz/repository/kacd-raw-hosted/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_COMMIT_REF_SLUG}/${CI_PIPELINE_ID}"
    - mkdir apps/build-extensions
  script:
    - curl -sL --user '${NEXUS_RAW_REPO}' "${NEXUS_REPO}/ldap-mappers.jar" -o apps/build-extensions/ldap-mappers.jar
  cache:
    - key: extensions
      policy: push
      paths:
        - apps/build-extensions
  tags:
    - global_runner_2

build-docker-keycloak:
  stage: build-docker
  image: 
    name: gcr.io/kaniko-project/executor:v1.9.1-debug
    entrypoint: [""]
  before_script:
    - echo $KANIKO_DOCKER_CONFIG | base64 -d > /kaniko/.docker/config.json
    - |-
      /kaniko/warmer \
        --cache-dir=${CI_PROJECT_DIR}/.cache \
        --image=quay.io/keycloak/keycloak:20.0.0
  script:
    - |-
      /kaniko/executor \
        --cache=true \
        --cache-dir=${CI_PROJECT_DIR}/.cache \
        --cache-ttl=4320h \
        --dockerfile=./apps/Dockerfile \
        --log-timestamp=true \
        --reproducible=true \
        --snapshot-mode=time \
        --use-new-run=true \
        --context=${CI_PROJECT_DIR}/apps \
        --destination=nexus.kacd.kz:5000/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/keycloak:${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}
  cache:
    - key: kaniko-cache-keycloak
      paths:
        - .cache/
    - key: extensions
      policy: pull
      paths:
        - build-extensions
  tags:
    - global_runner_2

build-docker-realm-controller:
  stage: build-docker
  image: 
    name: gcr.io/kaniko-project/executor:v1.9.1-debug
    entrypoint: [""]
  before_script:
    - echo $KANIKO_DOCKER_CONFIG | base64 -d > /kaniko/.docker/config.json
    - |-
      /kaniko/warmer \
        --cache-dir=${CI_PROJECT_DIR}/.cache \
        --image=amazoncorretto:17-alpine3.16-jdk
  script:
    - |-
      /kaniko/executor \
        --cache=true \
        --cache-dir=${CI_PROJECT_DIR}/.cache \
        --cache-ttl=4320h \
        --dockerfile=./apps/controllers/realm-controller/Dockerfile \
        --log-timestamp=true \
        --reproducible=true \
        --snapshot-mode=time \
        --use-new-run=true \
        --context=${CI_PROJECT_DIR}/apps/controllers/realm-controller \
        --destination=nexus.kacd.kz:5000/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/realm-controller:${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}
  cache:
    - key: kaniko-cache-realm-controller
      paths:
        - .cache/
  tags:
    - global_runner_2
       
k8s-dev-deploy:
  stage: dev-deploy
  image: nexus.kacd.kz:5000/core2471/docker-helm:master-632
  only:
    - dev
  environment:
    name: dev
  before_script:
    - cd apps
    - export RELEASE_NAME="${CI_PROJECT_NAME}"
    - mkdir -p /etc/deploy && export KUBECONFIG=/etc/deploy/config
    - echo ${KUBE_K8S_DEV_CONFIG} | base64 -d > /etc/deploy/config
  script:
    - |-
      helm upgrade --install ${RELEASE_NAME} ./.helm \
        --create-namespace --namespace="${CI_PROJECT_NAME}" \
        -f ./.helm/dev.yaml \
        --set image=nexus.kacd.kz:5000/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/keycloak:${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID} \
        --set realmController.image=nexus.kacd.kz:5000/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/realm-controller:${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}
  tags:
    - global_runner_2
