version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    command: ["start-dev"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_CACHE=ispn
    volumes:
      - ./conf/cache-ispn.xml:/opt/keycloak/conf/cache-ispn.xml
    ports:
      - 8080:8080

  redis:
    image: redis
    ports:
      - 6379:6379

  redis-insight:
    image: redislabs/redisinsight
    ports:
      - 8001:8001
