version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    command: ["start-dev"]
    environment:
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=admin
    - KC_DB=postgres
    - KC_DB_PASSWORD=keycloak
    - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak?user=postgres
    - KC_LOG_LEVEL=info
    - KC_FEATURES=declarative-user-profile
    volumes:
    - ./target/external-extensions-jar-with-dependencies.jar:/opt/keycloak/providers/external-extensions.jar:rw
    - ./realm.json:/opt/keycloak/data/import/realm.json:rw
    ports:
    - 8080:8080
  postgres:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=keycloak
    - POSTGRES_DB=keycloak
    ports:
    - 5438:5432
